version: "3"
services:
    frontend:
        image: fullbloodprince/muyihng:frontend
        container_name: frontend
        ports:
          - 3000:3000
        depends_on:
          - backend
    backend:
        image: fullbloodprince/muyihng:backend
        container_name: backend
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
